name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: pre-commit
        uses: markushinz/actions/pre-commit@v1.1.1
      - name: Set up Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "17.0.1"
      - name: Docker - Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Docker - Set up Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker - Login
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Workflow Mutex
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: markushinz/actions/workflow-mutex@v1.1.1
      - name: Version
        uses: markushinz/actions/version@v1.1.1
        with:
          minimum_version_command: cat version.txt
      - name: Docker - Build and Push
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            markushinz/example-server:v${{ env.VERSION }}
            markushinz/example-server:latest
      - name: Release
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" gh release create "v${VERSION}" --generate-notes
      - name: Deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: GITHUB_TOKEN="${{ secrets.TU_TOKEN }}" gh workflow run -R "${{ secrets.DEPLOY_REPO }}" cd -f "repository=markushinz/example-server" -f "tag=v${VERSION}" -f "merge=true"
