name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: pre-commit
        uses: markushinz/actions/pre-commit@v1.1.10
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 21
      - name: Docker - Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Docker - Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker - Login
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Version
        uses: markushinz/actions/version@v1.1.10
        with:
          minimum_version_command: cat version.txt
      - name: Docker - Build and Push
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            markushinz/example-server:v${{ env.VERSION }}
            markushinz/example-server:latest
      - name: Release
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" gh release create "v${VERSION}" --generate-notes
